<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-19 12:10
=======
# Generated by Django 4.2.2 on 2023-07-18 09:30
<<<<<<< HEAD
>>>>>>> 315d44705c95716b08e5cbdd9f5c7ef99fb89bec
=======
>>>>>>> Raman
>>>>>>> 3bece1c72049cfedf9d630b1e0030670119fa109

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('Educational', '0003_alter_educational_url'),
=======
    dependencies = [
        ("Educational", "0003_alter_educational_url"),
<<<<<<< HEAD
>>>>>>> 315d44705c95716b08e5cbdd9f5c7ef99fb89bec
=======
>>>>>>> Raman
>>>>>>> 3bece1c72049cfedf9d630b1e0030670119fa109
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name='educational',
            name='url',
=======
            model_name="educational",
            name="url",
<<<<<<< HEAD
>>>>>>> 315d44705c95716b08e5cbdd9f5c7ef99fb89bec
=======
>>>>>>> Raman
>>>>>>> 3bece1c72049cfedf9d630b1e0030670119fa109
        ),
    ]
