<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-19 12:10
=======
# Generated by Django 4.2.2 on 2023-07-18 09:30
>>>>>>> Raman

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('Educational', '0003_alter_educational_url'),
=======
    dependencies = [
        ("Educational", "0003_alter_educational_url"),
>>>>>>> Raman
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name='educational',
            name='url',
=======
            model_name="educational",
            name="url",
>>>>>>> Raman
        ),
    ]
