# Generated by Django 4.2.2 on 2023-07-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educational', '0003_alter_educational_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational',
            name='url',
        ),
    ]
