# Generated by Django 4.2.2 on 2023-07-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_name_post_author_post_content_and_more'),
        ('blog', '0003_remove_post_product_post_author_post_content_and_more'),
    ]

    operations = [
    ]
